//      TRAIN 1 VALUES

INSERT INTO Stopage values (1,"New Delhi","Start","10:30");
INSERT INTO Stopage values (1,"SABZI MANDI","10:40","10:41");
INSERT INTO Stopage values (1,"SONIPAT","11:30","11:33");
INSERT INTO Stopage values (1,"PANIPAT","12:00","12:01");
INSERT INTO Stopage values (1,"KURAKSHETRA","2:00","2:10");
INSERT INTO Stopage values (1,"AMBALA","2:40","3:00");

//Train 2 values

INSERT INTO Stopage values (2,"New Delhi","Start","10:30");
INSERT INTO Stopage values (2,"SABZI MANDI","10:40","10:41");
INSERT INTO Stopage values (2,"SONIPAT","11:30","11:33");
INSERT INTO Stopage values (2,"PANIPAT","12:00","12:01");
INSERT INTO Stopage values (2,"KURAKSHETRA","1:00","1:02");
INSERT INTO Stopage values (2,"AMBALA","1:20","1:30");
INSERT INTO Stopage values (2,"KARNAL","1:40","2:00");
INSERT INTO Stopage values (2,"CHANDIGARH","2:10","2:20");
INSERT INTO Stopage values (2,"LUDHIYANA","2:25","2:49");
INSERT INTO Stopage values (2,"PATHANKOT","2:50","3:00");



// TRAIN 3 VALUES

INSERT INTO Stopage values (3,"New Delhi","Start","10:30");
INSERT INTO Stopage values (3,"SABZI MANDI","10:40","10:41");
INSERT INTO Stopage values (3,"SONIPAT","11:30","11:33");
INSERT INTO Stopage values (3,"PANIPAT","12:00","12:01");
INSERT INTO Stopage values (3,"KURAKSHETRA","1:00","1:02");
INSERT INTO Stopage values (3,"AMBALA","1:20","1:30");
INSERT INTO Stopage values (3,"KARNAL","1:40","2:00");
INSERT INTO Stopage values (3,"CHANDIGARH","2:10","2:20");
INSERT INTO Stopage values (3,"LUDHIYANA","2:25","2:49");
INSERT INTO Stopage values (3,"PATHANKOT","2:50","2:52");
INSERT INTO Stopage values (3,"KHANNA","2:53","2:54");
INSERT INTO Stopage values (3,"JAMMU TABI","2:55","3:00");
